# Generated by Django 4.2.4 on 2023-08-04 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
